'use client';
import {useEffect,useState} from 'react';
import {Header,Footer} from '@/components/website';
import {request,dateLabel,timeLabel} from '@/lib/client';
export default function Account({isAdmin,signedIn,expires:initial,signIn,signOut,serviceError=''}:{isAdmin:boolean;signedIn:boolean;expires:number|null;signIn:string;signOut:string;serviceError?:string}){
 const [expires,setExpires]=useState(initial),[error,setError]=useState(serviceError),[checking,setChecking]=useState(false),[html,setHtml]=useState(''),[loading,setLoading]=useState(false);
 const active=isAdmin||!!(expires&&expires>Date.now()/1000);
 useEffect(()=>{const id=new URLSearchParams(location.search).get('session_id');if(!id||!signedIn)return;setChecking(true);request('checkout?session_id='+encodeURIComponent(id)).then(d=>{setExpires(d.expires);history.replaceState(null,'','/espace');if(!d.expires)setError('Votre paiement est encore en cours de confirmation. Actualisez cette page dans quelques instants.')}).catch(e=>setError(e.message)).finally(()=>setChecking(false))},[signedIn]);
 const loadApp=async()=>{setLoading(true);setError('');try{const r=await fetch('/application-contenu',{credentials:'same-origin'});if(!r.ok||!r.headers.get('content-type')?.includes('text/html'))throw new Error('L’application ne peut pas s’ouvrir pour le moment. Réessayez ou ouvrez-la dans un nouvel onglet.');const text=await r.text();if(!text.includes('startAccountApp'))throw new Error('Votre session doit être ouverte dans un nouvel onglet.');setHtml(text)}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 useEffect(()=>{if(active)void loadApp()},[active]);
 if(active)return <><div className="workspace-bar"><a href="/">FrancoRoute · Le site</a><span>{isAdmin?'Votre accès de gestion':expires?'Accès jusqu’au '+dateLabel(expires)+' à '+timeLabel(expires):''}</span><a href="/pratique">Mes heures de pratique</a><a href="/reserver">Réserver un premier appel</a>{isAdmin&&<a href="/gestion">Mes disponibilités</a>}<a href={signOut} target="_top">Déconnexion</a></div>{html?<iframe className="learning-frame" title="Application FrancoRoute — espace de préparation" srcDoc={html}/>:<main id="main" className="container section"><h1>{loading?'Ouverture de votre espace…':'Mon espace de préparation'}</h1><p className="error" role="alert">{error}</p><div className="actions"><button className="cta" disabled={loading} onClick={loadApp}>Réessayer</button><a className="text-link" href="/application-contenu" target="_blank" rel="noopener">Ouvrir l’application dans un nouvel onglet</a></div></main>}</>;
 return <><Header/><main id="main" className="container section legal"><div className="eyebrow">Mon espace FrancoRoute</div><h1>{checking?'Confirmation du paiement…':'Votre préparation commence ici.'}</h1><p className="lead">Retrouvez les questions G1, les situations G2 et G Full et les exercices de préparation avec l’accès de 3 semaines.</p><p className="error" role="alert">{error}</p>{!signedIn&&<p className="note">Utilisez la même adresse courriel que lors de votre achat pour retrouver votre accès.</p>}<div className="actions">{!signedIn?<a className="cta" href={signIn} target="_top">Me connecter à mon espace</a>:<a className="cta" href="/application#acces">Voir l’accès · 28 $ CA + taxes / 3 semaines</a>}{signedIn&&<a className="cta" href="/pratique">Réserver mes heures de pratique</a>}<a className="text-link" href="/reserver">Réserver un premier appel</a>{signedIn&&<a className="text-link" href={signOut} target="_top">Me déconnecter</a>}</div></main><Footer/></>;
}