'use client';
import {useEffect,useState} from 'react';
import {CalendarDays,Clock,Phone,MapPin,ChevronLeft,ChevronRight,CheckCircle2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {request,dateLabel,timeLabel,dayKey,torontoInstant} from '@/lib/client';
type Slot={id:string;starts:number};
export default function Booking(){
 const [slots,setSlots]=useState<Slot[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<Slot|null>(null),[date,setDate]=useState(''),[month,setMonth]=useState(()=>dayKey(Date.now()/1000).slice(0,7)),[busy,setBusy]=useState(false),[confirmation,setConfirmation]=useState<any>(null),[topic,setTopic]=useState('Orientation'),[admin,setAdmin]=useState(false);
 async function refresh(){setLoading(true);setError('');try{const d=await request('slots');setSlots(d.slots);if(d.slots.length){setMonth(dayKey(d.slots[0].starts).slice(0,7));setDate(dayKey(d.slots[0].starts));}}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{const q=new URLSearchParams(location.search);void refresh();const goal=q.get('objectif');if(goal)setTopic(goal==='G2'?'G2 / G':goal==='BDE'?'BDE':'G1');request('config').then(d=>setAdmin(!!d.admin)).catch(()=>{});},[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();Promise.resolve(context.registerTool({name:'list_first_call_slots',title:'Consulter les créneaux du premier appel',description:'Liste les disponibilités réelles de 15 minutes. Ne réserve aucun rendez-vous.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:any)=>{if(!input||Object.keys(input).length)throw new Error('Aucun paramètre attendu.');const d=await request('slots');setSlots(d.slots);return {timezone:'America/Toronto',slots:d.slots}}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[]);
 const [year,mon]=month.split('-').map(Number),count=new Date(Date.UTC(year,mon,0)).getUTCDate(),offset=(new Date(Date.UTC(year,mon-1,1)).getUTCDay()+6)%7;
 const availableDays=new Set(slots.map(s=>dayKey(s.starts)));
 function changeMonth(n:number){const d=new Date(Date.UTC(year,mon-1+n,1));setMonth(d.toISOString().slice(0,7));setDate('');setSelected(null)}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected){setError('Choisissez une date et un horaire avant de confirmer.');return}setBusy(true);setError('');const form=new FormData(e.currentTarget);try{const d=await request('bookings',{slotId:selected.id,name:form.get('name'),email:form.get('email'),phone:form.get('phone'),topic,consent:form.get('consent')==='on',website:form.get('website')});setConfirmation({...d,name:form.get('name')})}catch(e){setError((e as Error).message);setSelected(null);setSlots(await request('slots').then(d=>d.slots).catch(()=>slots));}finally{setBusy(false)}}
 function downloadIcs(){const stamp=(s:number)=>new Date(s*1000).toISOString().replace(/[-:]/g,'').replace('.000','');const url=location.origin+'/annuler?id='+confirmation.id+'&token='+confirmation.token;const text=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//FrancoRoute//Premier appel//FR','BEGIN:VEVENT','UID:'+confirmation.id+'@francoroute.com','DTSTAMP:'+stamp(Date.now()/1000),'DTSTART:'+stamp(confirmation.starts),'DTEND:'+stamp(confirmation.starts+900),'SUMMARY:Premier appel FrancoRoute','DESCRIPTION:Appel de 15 minutes. FrancoRoute vous appelle au numéro fourni. Pour annuler : '+url,'LOCATION:Par téléphone','END:VEVENT','END:VCALENDAR'].join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/calendar;charset=utf-8'}));a.download='premier-appel-francoroute.ics';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 return <section className="container section"><div className="eyebrow">Faisons connaissance</div><h1>Réserver<br/><em>un premier appel.</em></h1><p className="lead">15 minutes pour comprendre vos besoins, vous orienter et préparer la suite.</p>
 {confirmation?<div className="confirmation" role="status"><CheckCircle2 size={42}/><h2>Votre premier appel est réservé.</h2><p>{'Merci '+confirmation.name+'. FrancoRoute vous appellera au numéro indiqué.'}</p><strong>{dateLabel(confirmation.starts)} à {timeLabel(confirmation.starts)}</strong><p>Heure de l’Est · Durée : 15 minutes</p><div className="actions"><Button className="cta" onClick={downloadIcs}>Ajouter à mon calendrier</Button><a className="text-link" href={'/annuler?id='+confirmation.id+'&token='+confirmation.token}>Gérer ou annuler ce rendez-vous</a></div>{confirmation.outlookStatus==='pending'&&<p className="note">Votre appel est enregistré sur le site. Sa synchronisation avec le calendrier FrancoRoute est en cours.</p>}<p className="note">Conservez le rendez-vous dans votre calendrier : le lien d’annulation y sera inclus.</p></div>:
 <div className="booking-layout"><aside className="booking-about"><div className="phone-icon"><Phone/></div><h3>Un échange pour vous orienter</h3><p>Vous souhaitez commencer, reprendre confiance ou préparer une prochaine étape ? Nous faisons le point ensemble.</p><ul className="icon-list"><li><Clock/>15 minutes</li><li><Phone/>Nous vous appelons</li><li><MapPin/>Heure de l’Est</li></ul><div className="booking-steps"><h4>Au cours de cet appel</h4><p><b>1.</b> Votre parcours et votre objectif</p><p><b>2.</b> Vos besoins et vos questions</p><p><b>3.</b> Les prochaines étapes adaptées</p></div>{admin&&<a className="admin-calendar-link" href="/gestion">Ouvrir mes disponibilités</a>}</aside>
 <div className="booking-content"><div className="calendar-head"><h2>1. Choisissez un créneau</h2><span className="pill">15 min</span></div>
 {!loading&&slots.length===0&&<div className="calendar-empty"><strong>Aucun créneau n’est disponible pour le moment.</strong><p>Appelez-nous pour convenir d’un horaire.</p><div className="actions"><a className="cta" href="tel:+12263744883">Appeler le 226 374 4883</a>{admin&&<a className="text-link" href="/gestion">Ajouter mes créneaux</a>}</div></div>}
 <div className="calendar-and-times"><div><div className="month-nav"><Button variant="ghost" size="icon" onClick={()=>changeMonth(-1)} aria-label="Mois précédent"><ChevronLeft/></Button><strong>{new Intl.DateTimeFormat('fr-CA',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(year,mon-1,1)))}</strong><Button variant="ghost" size="icon" onClick={()=>changeMonth(1)} aria-label="Mois suivant"><ChevronRight/></Button></div><div className="calendar-grid" role="group" aria-label="Calendrier des disponibilités">{['L','M','M','J','V','S','D'].map((d,i)=><span className="week-day" key={'w'+i}>{d}</span>)}{Array.from({length:offset},(_,i)=><span key={'e'+i}/>)}{Array.from({length:count},(_,i)=>{const key=month+'-'+String(i+1).padStart(2,'0'),available=availableDays.has(key);return <button key={key} disabled={!available||loading} className={date===key?'selected':available?'available':''} aria-pressed={date===key} aria-label={key+(available?' — disponible':' — indisponible')} onClick={()=>{setDate(key);setSelected(null)}}>{i+1}</button>})}</div><p className="calendar-legend"><i/> Dates avec des disponibilités</p></div>
 <div className="times"><h4>{date?dateLabel(torontoInstant(date,'12:00')):'Les horaires disponibles'}</h4>{loading?<p role="status">Chargement des créneaux…</p>:slots.length===0?<a className="text-link" href="tel:+12263744883">Appelez le 226 374 4883</a>:!date?<p>Choisissez une date colorée pour voir les horaires.</p>:slots.filter(s=>dayKey(s.starts)===date).map(s=><Button key={s.id} variant="outline" className={selected?.id===s.id?'time selected':'time'} aria-pressed={selected?.id===s.id} onClick={()=>setSelected(s)}>{timeLabel(s.starts)}</Button>)}</div></div>
 <form onSubmit={submit}><div className="form-title"><h2>2. Vos coordonnées</h2><span>Vous pouvez remplir le formulaire avant de choisir un horaire.</span></div>{selected&&<p className="selected-summary"><CalendarDays size={18}/>{dateLabel(selected.starts)} · {timeLabel(selected.starts)}</p>}
 <fieldset disabled={busy}><div className="form-grid"><div><Label htmlFor="name">Votre nom</Label><Input id="name" name="name" autoComplete="name" required minLength={2} maxLength={100}/></div><div><Label htmlFor="phone">Votre téléphone</Label><Input id="phone" type="tel" name="phone" autoComplete="tel" required maxLength={25}/></div><div><Label htmlFor="email">Votre courriel</Label><Input id="email" type="email" name="email" autoComplete="email" required maxLength={254}/></div><div><Label htmlFor="topic">Votre objectif</Label><select id="topic" value={topic} onChange={e=>setTopic(e.target.value)}>{['Orientation','G1','BDE','G2 / G'].map(x=><option key={x} value={x}>{x==='G2 / G'?'G2 / G Full':x}</option>)}</select></div></div><div className="honeypot" aria-hidden="true"><label>Votre site<input name="website" tabIndex={-1} autoComplete="off"/></label></div><label className="check-label"><input type="checkbox" name="consent" required/><span>J’accepte que FrancoRoute utilise ces coordonnées pour organiser mon appel. <a href="/confidentialite" target="_blank">Confidentialité</a>.</span></label><Button type="submit" className="cta" disabled={!selected||busy}>{busy?'Réservation en cours…':'Confirmer mon premier appel'}</Button>{!selected&&<p className="form-hint">Choisissez un horaire dans le calendrier pour activer la confirmation.</p>}</fieldset></form><p className="error" role="alert">{error}</p></div></div>}</section>
}
