'use client';
import {useCallback,useEffect,useState} from 'react';
import {request,dateLabel,timeLabel} from '@/lib/client';
const hhmm=(m:number)=>String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0');
const value=(s:string)=>{const [h,m]=s.split(':').map(Number);return h*60+m;};
const statuses:Record<string,string>={pending:'Confirmation Outlook en attente',confirmed:'Confirmé',cancel_pending:'Annulation en attente',cancelled:'Annulé'};
export default function PracticeAdmin(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[cancelId,setCancelId]=useState('');
 const load=useCallback(()=>request('practice/admin').then(setData),[]);
 useEffect(()=>{load().catch(e=>setError(e.message));const result=new URLSearchParams(location.search).get('outlook');if(result==='error')setError('La connexion Outlook n’a pas abouti. Vérifiez les paramètres Microsoft et utilisez francoroute@outlook.com.');if(result==='connected')setMessage('Le calendrier Outlook a été connecté au site.');},[load]);
 async function act(path:string,body:any){setBusy(true);setMessage('');setError('');try{const r=await request('practice/'+path,body);if(r.url){location.assign(r.url);return true;}await load();setMessage(r.status==='pending'||r.status==='cancel_pending'?'Outlook n’a pas encore confirmé. Le créneau reste bloqué.':'Enregistrement effectué.');return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 async function credit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form);if(await act('credits',{email:f.get('email'),minutes:Number(f.get('hours'))*60,reference:f.get('reference'),paid:f.get('paid')==='on',eligible:f.get('eligible')==='on'}))form.reset();}
 return <section className="practice-area"><div className="eyebrow">Gestion · Outlook et pratique</div><h2>Votre calendrier et les heures de conduite</h2><p className="error" role="alert">{error}</p><p className="success" role="status">{message}</p>
 {!data?<p>{error?'La gestion des cours est indisponible. Les paramètres du serveur et la base de données doivent être activés.':'Chargement…'}</p>:<>
 <div className="admin-panel"><h3>Connexion Outlook</h3><p>{data.connection.connected?<>Connecté à <strong>{data.connection.account}</strong> · Calendrier <strong>{data.connection.calendar}</strong>.</>:data.connection.configured?'Le site est prêt à recevoir votre autorisation Microsoft.':'Les paramètres Microsoft du site doivent être renseignés dans Netlify avant la connexion.'}</p><p>Le site vérifie les occupations du calendrier et y inscrit les nouveaux rendez-vous. Les coordonnées restent réservées à FrancoRoute.</p><button className="cta" disabled={busy||!data.connection.configured} onClick={()=>act('connect',{})}>{data.connection.connected?'Renouveler la connexion Outlook':'Connecter francoroute@outlook.com'}</button><p className="note">Pour annuler un rendez-vous pris sur le site, utilisez la gestion ci-dessous. Une suppression directement dans Outlook ne restitue pas les heures du client.</p></div>
 <form className="admin-panel" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act('settings',{opening:value(String(f.get('opening'))),closing:value(String(f.get('closing')))});}}><h3>Horaires de pratique</h3><p>Lundi à dimanche · Heure de l’Est · Préavis de 2 h</p><div className="form-grid"><label>Ouverture<input name="opening" type="time" required step={900} defaultValue={hhmm(data.limits.opening)}/></label><label>Dernière fin de cours<input name="closing" type="time" required max="20:00" step={900} defaultValue={hhmm(data.limits.closing)}/></label></div><button className="cta" disabled={busy}>Enregistrer les horaires</button><p className="note">Pour fermer une journée ou une plage précise, ajoutez un événement marqué « Occupé » dans Outlook.</p></form>
 <form className="admin-panel" onSubmit={credit}><h3>Attribuer les heures d’un client qui a payé</h3><div className="form-grid"><label>Courriel utilisé pour son espace<input name="email" type="email" required autoComplete="off"/></label><label>Nombre d’heures<input name="hours" type="number" min="0.5" max="100" step="0.5" required/></label><label>Référence unique de la facture ou du paiement<input name="reference" required minLength={3} maxLength={150}/></label></div><label className="practice-check"><input name="paid" type="checkbox" required/>Je confirme que le paiement correspondant a été reçu.</label><label className="practice-check"><input name="eligible" type="checkbox" required/>Le client est autorisé à commencer la pratique ; les prérequis BDE sont complétés si applicables.</label><button className="cta" disabled={busy}>Ajouter ces heures payées</button><p className="note">Chaque référence ne peut être enregistrée qu’une fois. Indiquez au client de se connecter avec ce même courriel sur francoroute.com/pratique.</p></form>
 <div className="admin-panel"><h3>Soldes des clients</h3><div className="table-wrap"><table className="admin-table"><thead><tr><th>Courriel</th><th>Payées</th><th>Réservées / utilisées</th><th>Restantes</th></tr></thead><tbody>{data.credits.map((c:any)=><tr key={c.client_email}><td>{c.client_email}</td><td>{c.minutes/60} h</td><td>{c.used/60} h</td><td>{(c.minutes-c.used)/60} h</td></tr>)}</tbody></table></div></div>
 <div className="admin-panel"><h3>Rendez-vous reliés à Outlook</h3><p>Une confirmation en attente conserve le créneau et les heures. Réessayez la synchronisation si Outlook a été indisponible.</p><div className="table-wrap"><table className="admin-table"><thead><tr><th>Date</th><th>Client</th><th>Statut</th><th>Action</th></tr></thead><tbody>{data.appointments.map((a:any)=><tr key={a.id}><td>{dateLabel(a.starts)}<br/>{timeLabel(a.starts)} · {a.minutes} min</td><td>{a.name}<br/>{a.client_email}<br/>{a.phone}</td><td>{statuses[a.status]}</td><td>{['pending','cancel_pending'].includes(a.status)&&<button disabled={busy} className="text-link" onClick={()=>act('admin-retry',{id:a.id})}>Synchroniser</button>}{['pending','confirmed'].includes(a.status)&&(cancelId===a.id?<><p>Le client a-t-il été prévenu ?</p><button disabled={busy} className="text-link" onClick={()=>act('admin-cancel',{id:a.id}).then(()=>setCancelId(''))}>Oui, annuler</button><button className="text-link" onClick={()=>setCancelId('')}>Garder</button></>:<button disabled={busy} className="text-link" onClick={()=>setCancelId(a.id)}>Annuler</button>)}</td></tr>)}</tbody></table></div></div>
 </>}
 </section>;
}
